### ISSUE TITLE
Measuring and ranking the information content of marginalized joint posterior distributions

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#183]
@JosephCottam and I discussed today about how `load_and_calibrate_and_sample` returns samples of the joint posterior distribution over parameter space. Since we can't easily plot the `k`-dimensional function (where `k` = number of parameters), we plan to marginalize the distribution and show 1- or 2-d slices (univariate and bivariate/pairwise distributions). There would be be `2^k - 1` many such distributions. If so, then we'd want to show them in order of "interesting-ness".

One approach could be to sort these marginalized distributions by their KL divergence relative to the less interesting distribution (uniform). Concepts like "surprise" and "information content" probably come into play.

TA4 would like to have these "interesting-ness" scores computed by PyCIEMSS since it has access to the joint posterior "blob" while we only have samples from it.

**Comment by JosephCottam** [comment]
@liunelson How do you come up with `2^k-1` distributions?

If it is 1D distributions, that is `k`.
If it is 2D distributions, that is `k^2`.
If we are just talking about 1 and 2D distributions, that makes `k + k^2` distributions .
If we are talking about all distribution combinations, I think that is the powerset at `2^k`.

Otherwise, things look clear for now.

**Comment by liunelson** [comment]
@JosephCottam 
I just realized that I never answered your question!
I don't actually remember where I got `2^k - 1` but the point still stands `N ~ f(k) >> 1`

Might there be some progress on this feature request?

**Comment by SamWitty** [comment]
@liunelson , once #358 is merged then TA4 will have access to the full distribution object with an interface for evaluating posterior densities pointwise. At that time you'll be able to implement this kind of ranking in the TA4 services.

That being said, marginalizing arbitrary distributions will not be plausible because it requires solving an arbitrary integral equation in high dimensions. We are happy to help think through alternatives, or approximations using samples, but I don't think this is a feature that makes sense for us to have in the PyCIEMSS codebase.

**Comment by SamWitty** [comment]
Closing this issue now that #358 is merged. Still happy to discuss if/when you think this an appropriate task for our team.
