### ISSUE TITLE
`visuals/schemas` not included upon using 'pip install' 

### ISSUE THREAD

**Issue by fivegrant** [ciemss/pyciemss#371]
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/five/pyciemss-service/.venv/lib/python3.11/site-packages/pyciemss/visuals/schemas/trajectories.vg.json'
```

Hey @JosephCottam,

I'm upgrading the PyCIEMSS Service to use `v0.0.2` but it looks like a few JSONs were moved around and no longer install. The move to the schemas seems to be ignored by pip

**Comment by fivegrant** [comment]
cc @Tom-Szendrey

**Comment by fivegrant** [comment]
@JosephCottam for more context, I don't encounter the issue until running an operation. The install process itself does not fail

**Comment by JosephCottam** [comment]
Per the [install command given here](https://github.com/DARPA-ASKEM/pyciemss-service/blob/6844ec387932b7dceed96fedae1a6866ad6003fd/pyproject.toml#L38C2-L38C2) (changed it to 0.0.2), tested a fresh install of pyciemss from git....and it fails to copy those files.

Hypothesis: The schema files are not in a directory with any other python files, so maybe they are missed when the package is made.  This type of issue would NOT manifest on a local install (pip install -e .) because it links to the dev directory....

**Comment by JosephCottam** [comment]
The setup.cfg file was not picking up the data-files....I have a fix (but I'm not sure why it works).

I'm working on modifying our CI testing to install with a pull-from-the-current-hash to potentially catch issues like this in the future.
