### ISSUE TITLE
Calibrate does not seem to work when data is mapped to observables

### ISSUE THREAD

**Issue by sabinala** [ciemss/pyciemss#439]
Calibrate works fine when columns in a given dataset are mapped to state variables (like "I" or "H"), but fails when data columns are mapped to observables (like "infected" or "hospitalized"). Please see https://github.com/ciemss/pyciemss/blob/sa-load-data-tests/docs/source/sa-testing-notebooks/tests_for_load_data.ipynb for example.

**Comment by SamWitty** [comment]
@sabinala , could you please add a (currently failing) test to https://github.com/ciemss/pyciemss/blob/main/tests/test_interfaces.py that summarized the issue you're encountering? While making this PR, please add @pytest.skip so that the tests still "pass", even though one of them should fail. I (or someone else) will then follow up in a subsequent PR with a fix.

**Comment by sabinala** [comment]
I created more specific issue #447 to address the erroneous suffixes being added.
