### ISSUE TITLE
Add logging decorators back in 

### ISSUE THREAD

**Issue by djinnome** [ciemss/pyciemss#440]
@fivegrant requested that the logging decorators that exposed debugging and stacktrace info to Terarium in the older version of pyciemss be added to the new release

**Comment by fivegrant** [comment]
Thanks for opening this @djinnome! This is also a good issue but I was mainly wondering what was happening to the progress hook. It seems like they are missing after the refactor.

Since we're discussing the logging decorators, looks like they made it for [`ensemble-sample`](https://github.com/ciemss/pyciemss/blob/4ca1d6adce432c40427e25251a97925dd2584fe0/pyciemss/interfaces.py#L29) and [`sample`](https://github.com/ciemss/pyciemss/blob/4ca1d6adce432c40427e25251a97925dd2584fe0/pyciemss/interfaces.py#L147) but not [`calibrate`](https://github.com/ciemss/pyciemss/blob/4ca1d6adce432c40427e25251a97925dd2584fe0/pyciemss/interfaces.py#L302) so I think it's a one line change.

**Comment by SamWitty** [comment]
Addressed by #444
