### ISSUE TITLE
Installation instruction missing from README since repo refactor

### ISSUE THREAD

**Issue by liunelson** [ciemss/pyciemss#495]
The install steps are very useful and they have gone missing since the refactor.

**Comment by sabinala** [comment]
@akruel01 could you please take a look at [INSTALL.md](https://github.com/ciemss/pyciemss/blob/495-installation-instruction-missing-from-readme-since-repo-refactor/INSTALL.md), and make sure it's correct. I copied your instructions from here (https://github.com/ciemss/pyciemss/blob/sa-ensemble-eval/INSTALL.md), and just changed the notebook referenced in 13, not sure if anything else is out of date.

**Comment by akruel01** [comment]
Works for me at least. The only thing I would add @sabinala is that nowadays use Python 3.11.* not 3.10
